[package]
name = "pspf-launcher-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tar = "0.4"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
adler = "1.0"
tempfile = "3.0"
ed25519-dalek = "2.0"
pem = "3.0"
log = "0.4"
env_logger = "0.11"
