"""
TDD tests to verify cross-language compatibility between Python and Go for
critical cryptographic and binary format operations.
"""

import base64
import hashlib
from pathlib import Path
import struct
import subprocess

from cryptography.hazmat.primitives.asymmetric import ec

from flavor.compiler import ensure_go_binary
from flavor.crypto import sign_payload_hash
from flavor.models import FOOTER_STRUCT_FORMAT, PSPFV1Footer


def test_python_and_go_checksum_match(tmp_path: Path) -> None:
    """
    TDD Contract: Verifies that the Python FlavorFooter's Adler-32 checksum is
    identical to the Go implementation's hash/adler32.
    """
    footer_data = {
        "uv_offset": 1024,
        "uv_size": 204800,
        "python_offset": 205824,
        "python_size": 1048576,
        "metadata_offset": 1254400,
        "metadata_size": 4096,
        "payload_offset": 1258496,
        "payload_size": 524288,
        "signature_offset": 1782784,
        "signature_size": 71,
        "public_key_offset": 1782855,
        "public_key_size": 120,
        "pspf_version": 1,
        "flags": 1,
        "internal_footer_magic": 0x30505350,
        "language_emoji": b"\x00\x00\x00\x00",
        "type_emoji_1": b"\x00\x00\x00\x00",
        "type_emoji_2": b"\x00\x00\x00\x00",
    }
    footer_instance = PSPFV1Footer(**footer_data)
    python_checksum = footer_instance.footer_struct_checksum

    values_for_go = list(footer_data.values())
    values_for_go.insert(14, 0)
    packed_data_for_checksum = struct.pack(FOOTER_STRUCT_FORMAT, *values_for_go)
    b64_packed_data = base64.b64encode(packed_data_for_checksum).decode("ascii")

    packager_executable = ensure_go_binary("flavor-go")
    go_result = subprocess.run(
        [str(packager_executable), "test-utils", "adler32", b64_packed_data],
        capture_output=True,
        check=True,
    )
    go_checksum = struct.unpack("<I", go_result.stdout)[0]
    assert python_checksum == go_checksum


def test_python_signature_verifies_in_go(
    tmp_path: Path, public_key_pem: bytes, private_key: ec.EllipticCurvePrivateKey
) -> None:
    """
    TDD Contract: Verifies that an ECDSA signature generated by the Python crypto
    helper can be successfully verified by the Go implementation.
    """
    payload = b"This is the canonical payload for cross-language signature testing."
    payload_hash = hashlib.sha256(payload).digest()
    python_signature = sign_payload_hash(payload_hash, private_key)
    pub_key_path = tmp_path / "public.key"
    pub_key_path.write_bytes(public_key_pem)
    packager_executable = ensure_go_binary("flavor-go")
    verify_cmd = [
        str(packager_executable),
        "test-utils",
        "verify-ecdsa",
        "--public-key",
        str(pub_key_path),
        "--hash",
        payload_hash.hex(),
        "--signature",
        base64.b64encode(python_signature).decode("ascii"),
    ]
    result = subprocess.run(verify_cmd, capture_output=True, text=True, check=False)
    assert result.returncode == 0, f"Go verification failed: {result.stderr}"


# 📦🍜🧪🪄
