"""
Cross-language compatibility test suite for flavor.

This package contains tests that verify compatibility between:
- Python flavor (packager)
- Go flavor-go (packager)
- Rust flavor-rs (packager)
- Go flavor-launcher-go
- Rust flavor-launcher-rs

The tests ensure that:
1. All packagers produce identical packages given the same input
2. All launchers can run packages from any packager
3. Keys generated by any implementation work with all others
4. The PSPF format is consistent across implementations
"""


# 📦🍜🚀🪄
