#
# SPDX-FileCopyrightText: Copyright (c) 2025 provide.io llc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

"""flavor init — one-shot host setup for FlavorPack."""

from __future__ import annotations

from pathlib import Path

import click
from provide.foundation.console import pout

from flavor.config.dirs import get_config_dir, get_system_config_dir
from flavor.console import get_command_logger

log = get_command_logger("init")

_POLICY_TOML_SCAFFOLD = """\
# FlavorPack policy configuration
# Generated by: flavor init
#
# Uncomment and set values to override defaults.
# Operator policy can only TIGHTEN package-declared constraints, never loosen them.
#
# [trust]
# # Require all packages to be signed by a key in the trusted-keys store.
# # Default: false (warn only when store exists but key not found)
# require_trusted_key = false
#
# # Also check the OS keyring (macOS Keychain, Windows CertStore, Linux /etc/ssl)
# # for a certificate whose public key matches the package key fingerprint.
# # Default: false
# use_os_keychain = false
#
# [execution]
# # Block packages from running as root/Administrator.
# refuse_root = false
#
# # Maximum package age in days (computed from provenance.build_timestamp).
# # max_age_days = 365
#
# # Limit execution to these platforms (comma-separated).
# # allow_platforms = ["linux_amd64", "linux_arm64"]
#
# [attestation]
# # Block packages built without an attestation slot (SBOM + provenance).
# # Default: false
# require_sbom = false
"""


@click.command("init")
@click.option(
    "--global",
    "global_",
    is_flag=True,
    default=False,
    help="Set up system-wide config under /etc/flavor (requires root/sudo).",
)
def init_command(global_: bool) -> None:
    """Set up FlavorPack config directory structure on this host.

    Creates the trusted-keys directory and a commented-out policy.toml.
    Safe to run multiple times — existing files are never overwritten.
    """
    config_root: Path = get_system_config_dir() if global_ else get_config_dir()
    scope = "system" if global_ else "user"

    log.debug("Initializing FlavorPack config", scope=scope, root=str(config_root))

    # Create trusted-keys directory
    trusted_keys_dir = config_root / "trusted-keys"
    trusted_keys_dir.mkdir(parents=True, exist_ok=True)
    pout(f"✓ {trusted_keys_dir}")

    # Scaffold policy.toml (never overwrite)
    policy_file = config_root / "policy.toml"
    if not policy_file.exists():
        policy_file.write_text(_POLICY_TOML_SCAFFOLD, encoding="utf-8")
        pout(f"✓ {policy_file}  (scaffolded)")
    else:
        pout(f"  {policy_file}  (already exists, not modified)")

    pout(f"\nFlavorPack {scope} config initialised at {config_root}")
    if not global_:
        pout("  Add trusted keys with: flavor trust add <key.pub>")
        pout(f"  Edit policy:           {policy_file}")
    else:
        pout("  Add trusted keys with: sudo flavor trust add <key.pub> --global")
        pout(f"  Edit policy:           {policy_file}")


# 🌶️📦🔚
