#
# SPDX-FileCopyrightText: Copyright (c) 2025 provide.io llc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

"""flavor policy — manage and inspect launch-time execution policy."""

from __future__ import annotations

from datetime import UTC
import os
from pathlib import Path
import sys

import click
from provide.foundation.console import perr, pout

from flavor.config.dirs import get_policy_file
from flavor.config.policy import load_operator_policy, merge_policy, parse_package_policy
from flavor.console import get_command_logger

log = get_command_logger("policy")

_POLICY_TOML_SCAFFOLD = """\
# FlavorPack operator policy
# Generated by: flavor policy init
#
# Each setting here can only TIGHTEN package-declared constraints.
# An operator can refuse_root = true even if a package says false.
# An operator cannot allow a package to run that has its own refuse_root = true.
#
# [trust]
# # Require packages to be signed by a key in the trusted store.
# require_trusted_key = false
#
# # Also consult the OS certificate store for key trust (macOS/Windows).
# use_os_keychain = false
#
# [execution]
# # Block execution as root/Administrator.
# refuse_root = false
#
# # Maximum package age in days (build_timestamp from provenance).
# # max_age_days = 365
#
# # Restrict to these platforms (leave unset to allow all).
# # allow_platforms = ["linux_amd64", "linux_arm64"]
#
# [attestation]
# # Block packages that have no SBOM attestation slot.
# require_sbom = false
"""


@click.group("policy")
def policy_group() -> None:
    """Manage FlavorPack launch-time execution policy.

    Policy controls what packages are allowed to run on this host.
    Operator settings can only tighten package-declared constraints.
    """


@policy_group.command("init")
@click.option(
    "--global",
    "global_",
    is_flag=True,
    default=False,
    help="Scaffold system-wide policy at /etc/flavor/policy.toml (requires root).",
)
def policy_init(global_: bool) -> None:
    """Scaffold a policy.toml with all options commented out."""
    policy_file = get_policy_file(system=global_)
    policy_file.parent.mkdir(parents=True, exist_ok=True)

    if policy_file.exists():
        pout(f"  {policy_file}  (already exists, not modified)")
    else:
        policy_file.write_text(_POLICY_TOML_SCAFFOLD, encoding="utf-8")
        pout(f"✓ {policy_file}  (scaffolded)")

    scope = "system" if global_ else "user"
    pout(f"\nFlavorPack {scope} policy file ready. Edit it to enforce constraints.")


@policy_group.command("show")
def policy_show() -> None:
    """Print the effective policy (operator defaults) for this host."""
    op = load_operator_policy()
    pout("[trust]")
    pout(f"  require_trusted_key = {str(op.require_trusted_key).lower()}")
    pout(f"  use_os_keychain     = {str(op.use_os_keychain).lower()}")
    pout("")
    pout("[execution]")
    pout(f"  refuse_root     = {str(op.refuse_root).lower()}")
    if op.max_age_days is not None:
        pout(f"  max_age_days    = {op.max_age_days}")
    else:
        pout("  max_age_days    = (no limit)")
    if op.allow_platforms:
        pout(f"  allow_platforms = {op.allow_platforms}")
    else:
        pout("  allow_platforms = (all platforms)")
    pout("")
    pout("[attestation]")
    pout(f"  require_sbom = {str(op.require_sbom).lower()}")


@policy_group.command("check")
@click.argument("package_file", type=click.Path(exists=True, dir_okay=False, resolve_path=True))
def policy_check(package_file: str) -> None:
    """Dry-run: would this package be allowed to run on this host?"""
    from datetime import datetime

    from flavor.psp.format_2025.reader import PSPFReader

    pkg_path = Path(package_file)
    with PSPFReader(pkg_path) as reader:
        metadata = reader.read_metadata()
        index = reader.read_index()

    pkg_raw = metadata.get("policy", {})
    pkg_policy = parse_package_policy(pkg_raw)
    op_policy = load_operator_policy()
    effective = merge_policy(pkg_policy, op_policy)

    current_platform = _get_current_platform()
    if effective.platforms and current_platform not in effective.platforms:
        perr(f"❌ Platform not permitted: {current_platform} not in {effective.platforms}")
        sys.exit(1)

    if effective.refuse_root and _is_root():
        perr("❌ Package refuses to run as root")
        sys.exit(1)

    if effective.max_age_days is not None:
        build_ts = index.build_timestamp
        if build_ts > 0:
            age_days = (datetime.now(UTC).timestamp() - build_ts) / 86400
            if age_days > effective.max_age_days:
                perr(f"❌ Package is {int(age_days)} days old; policy requires max {effective.max_age_days}")
                sys.exit(1)

    missing = [var for var in effective.require_env if not os.environ.get(var)]
    if missing:
        for var in missing:
            perr(f"❌ Required environment variable not set: {var}")
        sys.exit(1)

    pout("✓ Package would be allowed on this host.")
    pout(f"  Platform: {current_platform}")
    pout(f"  refuse_root: {effective.refuse_root}")
    pout(f"  max_age_days: {effective.max_age_days or '(no limit)'}")


def _get_current_platform() -> str:
    import platform as _platform

    os_name = (
        "linux" if sys.platform.startswith("linux") else ("darwin" if sys.platform == "darwin" else "windows")
    )
    machine = _platform.machine().lower()
    arch = "arm64" if machine in ("arm64", "aarch64") else "amd64"
    return f"{os_name}_{arch}"


def _is_root() -> bool:
    try:
        return os.geteuid() == 0  # type: ignore[attr-defined,unused-ignore]
    except AttributeError:
        return False  # Windows


# 🌶️📦🔚
