"""
Cross-language compatibility tests for key generation.

Tests that keys generated by any packager can be used by any other packager.
"""

import os
from pathlib import Path
import shutil
import subprocess
import tempfile

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
import pytest

from flavor.compiler import ensure_go_binary


@pytest.fixture(scope="module")
def keygen_binaries():
    """Get all available keygen implementations as callables."""
    binaries = {}

    # Python uses flavor module
    def python_keygen_cmd(key_dir):
        return ["python", "-m", "flavor", "keygen", "--out-dir", str(key_dir)]

    binaries["python"] = python_keygen_cmd

    # Go packager
    go_packager = ensure_go_binary("flavor-go")

    def go_keygen_cmd(key_dir):
        # Go keygen does not support --out-dir, so we run it in the target directory
        return [str(go_packager), "keygen"]

    binaries["go"] = go_keygen_cmd

    # Rust packager if available
    rust_dir = (
        Path(__file__).parent.parent.parent
        / "src"
        / "flavor"
        / "rust"
        / "flavor-packager-rs"
    )
    if shutil.which("cargo") and rust_dir.exists():
        subprocess.run(
            ["cargo", "build", "--release"],
            cwd=rust_dir,
            check=True,
            capture_output=True,
        )
        rust_binary = rust_dir / "target" / "release" / "flavor-rs"
        if rust_binary.exists():

            def rust_keygen_cmd(key_dir):
                return [str(rust_binary), "keygen", "--out-dir", str(key_dir)]

            binaries["rust"] = rust_keygen_cmd

    return binaries


@pytest.fixture(scope="module")
def packager_binaries():
    """Get all available packager implementations."""
    binaries = {}

    # Python uses flavor module
    binaries["python"] = ["python", "-m", "flavor"]

    # Go packager
    go_packager = ensure_go_binary("flavor-go")
    binaries["go"] = [str(go_packager)]

    # Rust packager if available
    rust_dir = (
        Path(__file__).parent.parent.parent
        / "src"
        / "flavor"
        / "rust"
        / "flavor-packager-rs"
    )
    if shutil.which("cargo") and rust_dir.exists():
        subprocess.run(
            ["cargo", "build", "--release"],
            cwd=rust_dir,
            check=True,
            capture_output=True,
        )
        rust_binary = rust_dir / "target" / "release" / "flavor-rs"
        if rust_binary.exists():
            binaries["rust"] = [str(rust_binary)]

    return binaries


def load_and_verify_keys(key_dir):
    """Load and verify ECDSA keys from a directory."""
    private_key_path = key_dir / "provider-private.key"
    public_key_path = key_dir / "provider-public.key"

    assert private_key_path.exists(), "Private key not found"
    assert public_key_path.exists(), "Public key not found"

    # Load private key
    with open(private_key_path, "rb") as f:
        private_key = serialization.load_pem_private_key(
            f.read(), password=None, backend=default_backend()
        )

    # Load public key
    with open(public_key_path, "rb") as f:
        public_key = serialization.load_pem_public_key(
            f.read(), backend=default_backend()
        )

    # Verify they're ECDSA keys
    assert isinstance(private_key, ec.EllipticCurvePrivateKey)
    assert isinstance(public_key, ec.EllipticCurvePublicKey)

    # Verify they're P-256 curve
    assert isinstance(private_key.curve, ec.SECP256R1)
    assert isinstance(public_key.curve, ec.SECP256R1)

    # Verify the public key matches the private key
    derived_public = private_key.public_key()
    assert derived_public.public_numbers() == public_key.public_numbers()

    return private_key, public_key


class TestKeygenCompatibility:
    """Test key generation compatibility across implementations."""

    def test_all_keygens_produce_valid_keys(self, keygen_binaries) -> None:
        """Test that all implementations generate valid ECDSA P-256 keys."""
        for name, cmd_generator in keygen_binaries.items():
            with tempfile.TemporaryDirectory() as temp_dir:
                key_dir = Path(temp_dir) / "keys"
                key_dir.mkdir()

                full_cmd = cmd_generator(key_dir)

                # Determine cwd for subprocess based on keygen name
                cwd = key_dir if name == "go" else None

                result = subprocess.run(
                    full_cmd, capture_output=True, text=True, cwd=cwd
                )
                assert result.returncode == 0, f"{name} keygen failed: {result.stderr}"

                # Verify keys
                private_key, public_key = load_and_verify_keys(key_dir)

                # Test that we can sign and verify with the keys
                from cryptography.hazmat.primitives import hashes

                test_data = b"test data for signing"
                signature = private_key.sign(test_data, ec.ECDSA(hashes.SHA256()))

                # Should not raise exception
                public_key.verify(signature, test_data, ec.ECDSA(hashes.SHA256()))

    def test_keys_interoperable_for_packaging(
        self, keygen_binaries, packager_binaries, tmp_path
    ) -> None:
        """Test that keys from one implementation work with other packagers."""
        if len(keygen_binaries) < 2:
            pytest.skip("Need at least 2 implementations for cross-testing")

        # Create test provider
        src_dir = tmp_path / "src" / "key_test"
        src_dir.mkdir(parents=True)
        (src_dir / "__init__.py").write_text('"""Key test."""')
        (src_dir / "main.py").write_text('def serve(): print("Key test")')

        pyproject = tmp_path / "pyproject.toml"
        pyproject.write_text("""
[project]
name = "key-test"
version = "1.0.0"

[tool.pspf]
provider_name = "keytest"
entry_point = "key_test.main:serve"
""")

        # Generate keys with each implementation
        all_keys = {}
        for gen_name, gen_cmd_generator in keygen_binaries.items():
            key_dir = tmp_path / f"keys_{gen_name}"
            key_dir.mkdir()

            full_cmd = gen_cmd_generator(key_dir)

            # Determine cwd for subprocess based on keygen name
            cwd = key_dir if gen_name == "go" else None

            subprocess.run(full_cmd, check=True, capture_output=True, cwd=cwd)
            all_keys[gen_name] = key_dir

        # Try to build packages with each packager using keys from each generator
        for packager_name, packager_base_cmd in packager_binaries.items():
            for keygen_name, key_dir in all_keys.items():
                # Update pyproject with key paths
                config = pyproject.read_text()
                config += f"""
[tool.pspf.signing]
private_key_path = "{key_dir / "provider-private.key"}"
public_key_path = "{key_dir / "provider-public.key"}"
"""
                pyproject.write_text(config)

                # Try to build
                if packager_name == "python":
                    build_cmd = [*packager_base_cmd, "package", "--manifest", str(pyproject)]
                    build_cwd = None
                else:
                    output = tmp_path / f"test_{packager_name}_{keygen_name}.flavor"
                    build_cmd = [*packager_base_cmd, "build", "--out", str(output), "--payload-dir", str(tmp_path), "--package-key", str(key_dir / "provider-private.key"), "--public-key", str(key_dir / "provider-public.key"), "--launcher-bin", str(ensure_go_binary("flavor-launcher-go"))]
                    build_cwd = (
                        tmp_path if packager_name == "go" else None
                    )  # Assuming go packager also needs cwd for build

                result = subprocess.run(
                    build_cmd, capture_output=True, text=True, cwd=build_cwd
                )
                assert result.returncode == 0, (
                    f"{packager_name} packager failed with keys from {keygen_name}: {result.stderr}"
                )


class TestKeygenDeterminism:
    """Test keygen behavior and options."""

    @pytest.mark.parametrize("impl_name", ["python", "go", "rust"])
    def test_keygen_creates_different_keys(self, keygen_binaries, impl_name) -> None:
        """Test that running keygen twice creates different keys."""
        if impl_name not in keygen_binaries:
            pytest.skip(f"{impl_name} implementation not available")

        cmd_generator = keygen_binaries[impl_name]
        keys = []

        for _i in range(2):
            with tempfile.TemporaryDirectory() as temp_dir:
                key_dir = Path(temp_dir) / "keys"
                key_dir.mkdir()

                full_cmd = cmd_generator(key_dir)

                # Determine cwd for subprocess based on keygen name
                cwd = key_dir if impl_name == "go" else None

                subprocess.run(full_cmd, check=True, capture_output=True, cwd=cwd)

                # Read private key
                with open(key_dir / "provider-private.key", "rb") as f:
                    private_key_pem = f.read()

                keys.append(private_key_pem)

        # Keys should be different
        assert keys[0] != keys[1], f"{impl_name} keygen produced identical keys"

    def test_keygen_output_files(self, keygen_binaries) -> None:
        """Test that all implementations create the expected output files."""
        for (
            name,
            cmd_generator,
        ) in keygen_binaries.items():  # Renamed cmd to cmd_generator for clarity
            with tempfile.TemporaryDirectory() as temp_dir:
                key_dir = Path(temp_dir) / "keys"
                key_dir.mkdir()

                full_cmd = cmd_generator(key_dir)  # Use the callable directly

                # Determine cwd for subprocess based on keygen name
                cwd = key_dir if name == "go" else None

                subprocess.run(full_cmd, check=True, capture_output=True, cwd=cwd)

                # Check files exist with correct names
                assert (key_dir / "provider-private.key").exists()
                assert (key_dir / "provider-public.key").exists()

                # Check file permissions (private key should be 0600)
                import stat

                private_stat = os.stat(key_dir / "provider-private.key")
                assert stat.S_IMODE(private_stat.st_mode) == 0o600


# 📦🍜🧪🪄
